name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  db:
    name: DB / ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MySQL 5
            database: mysql:5
            connection: 'mysql+mysqldb://buildbot:buildbot@127.0.0.1:3306/bbtest?storage_engine=InnoDB'
            check: mysqladmin ping

    env:
      BUILDBOT_TEST_DB_URL: ${{ matrix.connection }}
      BUILDBOT_TEST_PROXY_CONNECTION_STRING: 'tcp:127.0.0.1:3128'

    services:
      database:
        image: ${{ matrix.database }}
        env:
          MYSQL_USER: buildbot
          MYSQL_PASSWORD: buildbot
          MYSQL_DATABASE: bbtest
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          POSTGRES_USER: buildbot
          POSTGRES_PASSWORD: buildbot
          POSTGRES_DB: bbtest
        ports:
          - '3306:3306'
          - '5432:5432'
        options: --health-cmd "${{ matrix.check }}" --health-interval 10s --health-timeout 5s --health-retries 10

      proxy:
        image: datadog/squid
        ports:
          - '3128:3128'

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get install aspell aspell-en enchant iamerican ispell

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt', 'requirements-cidb.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - run: pip install -U pip
      - run: pip install -r requirements-ci.txt -r requirements-cidb.txt

      # run real db tests under coverage to have several merging coverage report
      # https://github.com/codecov/support/wiki/Merging-Reports
      - run: coverage run --rcfile=.coveragerc $(which trial) --reporter=text --rterrors buildbot.test buildbot_worker.test

      - run: codecov
